### PR TITLE
test: add test for #42

### LINKED ISSUE #42: incorrect space not fixed for variable names
expect both of these:
```sass
$c-primary :#000000
// and
$c-primary : #000000
```
to be fixed to:
```sass
$c-primary: #000000
```

but they don't get auto fixed

### PR DESCRIPTION
**Pull request by mesqueeb**
fixes #42

### CODE REVIEW

**Comment by mesqueeb** [comment]
@TheRealSyler I don't agree with the CodeFactor warning, because those trailing whitespaces are part of the test.......

image

**Comment by TheRealSyler** [comment]
@mesqueeb the code factor thingy doesn't understand that its inside a string, you can just ignore that, its not important the it passes.

**Comment by mesqueeb** [comment]
Do you like pr? It's rdy !

**Review by TheRealSyler — APPROVED** [review]

**Comment by TheRealSyler** [comment]
when there is a regex that needs to be changed you should change it in the `suf-regex` package instead of adding a new function other than that the pr looks good, thanks for contributing.

**Pull request merged**
