### PR TITLE
test: add test for #43

### LINKED ISSUE #43: unwanted spaces are added in front of variable names
Since the last release, variable names that are not in the start of the file get two unwanted spaces added in front of them...

See gif:

### PR DESCRIPTION
**Pull request by mesqueeb**
fixes #43

### CODE REVIEW

**Comment by TheRealSyler** [comment]
thanks for contributing, your fix doesn't cover the modified test, we want the variables to snap to the nearest valid position, your implementation brakes if you use more than 2 spaces.

your solution fails with this code and if we use 4 spaces.
```sass
.test
    color: black
   $a: black
```
this is how your solution formatts the code above
```sass
.test
    color: black
   $a: black
```

my implementation might also have some issues, but for now this good enough, thanks again for taking the time to contribute.

**Review by TheRealSyler — APPROVED** [review]

**Comment by TheRealSyler** [comment]
thanks for contributing, your fix doesn't cover the modified test, we want the variables to snap to the nearest valid position, your implementation brakes if you use more than 2 spaces.

your solution fails with this code and if we use 4 spaces.
```sass
.test
    color: black
   $a: black
```
this is how your solution formatts the code above
```sass
.test
    color: black
   $a: black
```

my implementation might also have some issues, but for now this good enough, thanks again for taking the time to contribute.

**Comment by mesqueeb** [comment]
@TheRealSyler i see! Is defining a variable with indentation valid ? I didn't know! Why would anyone define a variable next to regular props? as opposed to outside of the block without indentation. :O

**Comment by TheRealSyler** [comment]
yes im pretty sure you can have block scoped variables.

**Pull request merged**
