### PR TITLE
Web components

### PR DESCRIPTION
**Pull request by binaryben**
I made a naive attempt to get web components working (#67) based on the @TheRealSyler's mention of amending the right regex. Unfortunately, I either have the wrong regex or it's more complicated to implement than anticipated as it breaks a lot of tests. Feedback and pointers in the right direction would be appreciated.

### CODE REVIEW

**Comment by binaryben** [comment]
Apologies, I added the gitmoji's out of habit on personal projects

**Comment by TheRealSyler** [comment]
@binaryben I Updated your regex addition, it should work now, can you please add a couple of full test with web components after that it should be ready to merge.



> Apologies, I added the gitmoji's out of habit on personal projects

No worries, i don't really care about the commit format for this project.

**Comment by binaryben** [comment]
Done @TheRealSyler. Let me know if there is any other tests that should be written please.

Will merging this automatically update the VSCode (and Open VSX Marketplace) extension out of interest?

**Comment by TheRealSyler** [comment]
@binaryben Thanks for the pr, ill make a new release for it.


> Will merging this automatically update the VSCode (and Open VSX Marketplace) extension out of interest?
no i have to release a new sass-formatter version then i have to update the extension to use the new version.

**Comment by binaryben** [comment]
Thank you for the release! Works well 👍🏼

**Pull request merged**
